---
title: "p8105_hw5_jg5038"
author: "Julia Gray"
date: "2025-11-05"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

#these options were messing up my fig.height 
#knitr::opts_chunk$set(
#  fig.width = 6,
#  fig.asp = .6
#)

knitr::opts_chunk$set(
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1: Birthday problem

```{r}
#define data generating mechanism
birthdays = sample(1:365, 5, replace = TRUE)

#run the analysis
repeated_bday = length(unique(birthdays)) < 5

#return the result
repeated_bday
```


put this in a function

```{r}
bday_sim = function(n_room) {
  
  birthdays = sample(1:365, n_room, replace = TRUE)

  repeated_bday = length(unique(birthdays)) < n_room

  repeated_bday
}

#bday_sim(20)
```

```{r}
bday_sim_results = 
  expand_grid(
    bdays = 5:50,
    iter = 1:1000
  ) |> 
  mutate(
    result = map_lgl(bdays, bday_sim)
  ) |> 
  group_by (
    bdays
  ) |> 
  summarize(
    prob_repeat = mean(result)
  )
```

Plot results (test):

```{r}
bday_sim_results |> 
  ggplot(aes(x = bdays, y = prob_repeat)) +
  geom_point() +
  geom_line()
```

### Problem 2
Problem 2 = if you're study is underpowered, you're going to overestimate effect size. If only see significant results = not getting idea of what real value is

